//HintName: Solution.g.cs
// <auto-generated/>

using Fallout.Persistence.Solution.Model;
using Fallout.Solutions;
using Fallout.Common.IO;
using System.Runtime.CompilerServices;

internal class Solution(SolutionModel model, AbsolutePath path) : Fallout.Solutions.Solution(model, path)
{
    public Fallout.Solutions.Project ꞏbuild => this.GetProject("_build");
    public Fallout.Solutions.Project FalloutꞏBuild => this.GetProject("Fallout.Build");
    public Fallout.Solutions.Project FalloutꞏBuildꞏShared => this.GetProject("Fallout.Build.Shared");
    public Fallout.Solutions.Project FalloutꞏBuildꞏSpecs => this.GetProject("Fallout.Build.Specs");
    public Fallout.Solutions.Project FalloutꞏCli => this.GetProject("Fallout.Cli");
    public Fallout.Solutions.Project FalloutꞏCliꞏSpecs => this.GetProject("Fallout.Cli.Specs");
    public Fallout.Solutions.Project FalloutꞏCommon => this.GetProject("Fallout.Common");
    public Fallout.Solutions.Project FalloutꞏCommonꞏSpecs => this.GetProject("Fallout.Common.Specs");
    public Fallout.Solutions.Project FalloutꞏComponents => this.GetProject("Fallout.Components");
    public Fallout.Solutions.Project FalloutꞏComponentsꞏSpecs => this.GetProject("Fallout.Components.Specs");
    public Fallout.Solutions.Project FalloutꞏConsumerꞏLocal => this.GetProject("Fallout.Consumer.Local");
    public Fallout.Solutions.Project FalloutꞏConsumerꞏNuGet => this.GetProject("Fallout.Consumer.NuGet");
    public Fallout.Solutions.Project FalloutꞏCore => this.GetProject("Fallout.Core");
    public Fallout.Solutions.Project FalloutꞏCoreꞏSpecs => this.GetProject("Fallout.Core.Specs");
    public Fallout.Solutions.Project FalloutꞏMigrate => this.GetProject("Fallout.Migrate");
    public Fallout.Solutions.Project FalloutꞏMigrateꞏAnalyzers => this.GetProject("Fallout.Migrate.Analyzers");
    public Fallout.Solutions.Project FalloutꞏMigrateꞏAnalyzersꞏSpecs => this.GetProject("Fallout.Migrate.Analyzers.Specs");
    public Fallout.Solutions.Project FalloutꞏMigrateꞏSpecs => this.GetProject("Fallout.Migrate.Specs");
    public Fallout.Solutions.Project FalloutꞏMSBuildTasks => this.GetProject("Fallout.MSBuildTasks");
    public Fallout.Solutions.Project FalloutꞏPersistenceꞏSolution => this.GetProject("Fallout.Persistence.Solution");
    public Fallout.Solutions.Project FalloutꞏPersistenceꞏSolutionꞏBenchmarks => this.GetProject("Fallout.Persistence.Solution.Benchmarks");
    public Fallout.Solutions.Project FalloutꞏProjectModel => this.GetProject("Fallout.ProjectModel");
    public Fallout.Solutions.Project FalloutꞏProjectModelꞏSpecs => this.GetProject("Fallout.ProjectModel.Specs");
    public Fallout.Solutions.Project FalloutꞏSolution => this.GetProject("Fallout.Solution");
    public Fallout.Solutions.Project FalloutꞏSolutionꞏSpecs => this.GetProject("Fallout.Solution.Specs");
    public Fallout.Solutions.Project FalloutꞏSourceGenerators => this.GetProject("Fallout.SourceGenerators");
    public Fallout.Solutions.Project FalloutꞏSourceGeneratorsꞏSpecs => this.GetProject("Fallout.SourceGenerators.Specs");
    public Fallout.Solutions.Project FalloutꞏTooling => this.GetProject("Fallout.Tooling");
    public Fallout.Solutions.Project FalloutꞏToolingꞏGenerator => this.GetProject("Fallout.Tooling.Generator");
    public Fallout.Solutions.Project FalloutꞏToolingꞏSpecs => this.GetProject("Fallout.Tooling.Specs");
    public Fallout.Solutions.Project FalloutꞏUtilities => this.GetProject("Fallout.Utilities");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏIOꞏCompression => this.GetProject("Fallout.Utilities.IO.Compression");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏIOꞏGlobbing => this.GetProject("Fallout.Utilities.IO.Globbing");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏNet => this.GetProject("Fallout.Utilities.Net");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏSpecs => this.GetProject("Fallout.Utilities.Specs");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏTextꞏJson => this.GetProject("Fallout.Utilities.Text.Json");
    public Fallout.Solutions.Project FalloutꞏUtilitiesꞏTextꞏYaml => this.GetProject("Fallout.Utilities.Text.Yaml");
    public Fallout.Solutions.Project NukeꞏBuild => this.GetProject("Nuke.Build");
    public Fallout.Solutions.Project NukeꞏCommon => this.GetProject("Nuke.Common");
    public Fallout.Solutions.Project NukeꞏCommonꞏShimꞏSpecs => this.GetProject("Nuke.Common.Shim.Specs");
    public Fallout.Solutions.Project NukeꞏComponents => this.GetProject("Nuke.Components");
    public Fallout.Solutions.Project NukeꞏComponentsꞏShimꞏSpecs => this.GetProject("Nuke.Components.Shim.Specs");
    public Fallout.Solutions.Project NukeꞏConsumer => this.GetProject("Nuke.Consumer");

    public ꞏꞏ01ꞏtest ꞏ01ꞏtest => Unsafe.As<ꞏꞏ01ꞏtest>(this.GetSolutionFolder("01-test"));
    public ꞏmisc misc => Unsafe.As<ꞏmisc>(this.GetSolutionFolder("misc"));

    internal class ꞏꞏ01ꞏtest(SolutionFolderModel model, Fallout.Solutions.Solution solution) : Fallout.Solutions.SolutionFolder(model, solution)
    {
    
    
    }
    internal class ꞏmisc(SolutionFolderModel model, Fallout.Solutions.Solution solution) : Fallout.Solutions.SolutionFolder(model, solution)
    {
    
    
    }
}